machines = {
  "node01" => {"memory"=>"1024", "cpu"=>"1", "image"=>"bento/ubuntu-22.04", "ip"=>"192.168.56.11"},
  "node02" => {"memory"=>"1024", "cpu"=>"1", "image"=>"bento/ubuntu-22.04", "ip"=>"192.168.56.12"},
  "node03" => {"memory"=>"1024", "cpu"=>"1", "image"=>"bento/ubuntu-22.04", "ip"=>"192.168.56.13"},
  "node04" => {"memory"=>"1024", "cpu"=>"1", "image"=>"bento/ubuntu-22.04", "ip"=>"192.168.56.14"}
}

Vagrant.configure("2") do |config|
  machines.each do |name, conf|
    config.vm.define name do |machine|
      machine.vm.box      = conf["image"]
      machine.vm.hostname = name
      machine.vm.network "private_network",
        ip:      conf["ip"],
        netmask: "255.255.255.0"

      machine.vm.provider "virtualbox" do |vb|
        vb.name    = name
        vb.memory  = conf["memory"]
        vb.cpus    = conf["cpu"]
      end

      machine.vm.provision "shell", path: "instalar-docker.sh"
    end
  end
end
