version: "3.8"

services:
  db:
    image: mysql:9.3
    environment:
      MYSQL_ROOT_PASSWORD: "senha123"
      MYSQL_DATABASE: "testdb"
    ports:
      - "3306:3306"
    volumes:
      - /data/mysql-compose:/var/lib/mysql

  web:
    build: .
    depends_on:
      - db
    ports:
      - "8080:80"
    volumes:
      - ./html:/var/www/html

  adminer:
    image: adminer
    depends_on:
      - db
    ports:
      - "8081:8080"